os: linux
sudo: required
language: minimal
services:
  - docker

before_script:
  - docker --version
  - docker-compose --version
  - chmod +x bin/{detect,compile}

script:
  - docker-compose up --abort-on-container-exit --exit-code-from test
